version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: vitae_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Carga automática del esquema al iniciar
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    image: vitae:v1
    platform: linux/amd64
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=vitae_db
      - JWT_SECRET=VV/T/n1zCSOUqPBtBbI4+Ub/NYnHvA8FP9WPSM8QKF4=
    depends_on:
      - db

volumes:
  db_data:
